"""order status and inventory history

Revision ID: 377398800f5e
Revises: 4b9647ef29f0
Create Date: 2026-10-06 22:37:43.156210

Append-only change history, as two specific tables rather than one generic
audit table, so each has typed columns and real foreign keys:
- `order_status_history`: every order status change, with actor, from/to
  status (the existing `order_status` type, reused) and a source enum
  (`order_status_change_source`).
- `inventory_history`: every manual stock adjust/level set, with actor,
  reason and the values before/after (`inventory_change_kind`).

Autogenerated, then reviewed: autogenerate rendered `order_status` as a
type to create (it already exists), and its downgrade did not drop the two
new enum types. Both are fixed by hand.

No backfill: history starts when this is applied. Downgrade drops both
tables and their rows.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Reuses the existing `order_status` type (orders.status); never create or drop it here.
_EXISTING_ORDER_STATUS = postgresql.ENUM(name="order_status", create_type=False)

# revision identifiers, used by Alembic.
revision: str = "377398800f5e"
down_revision: str | Sequence[str] | None = "4b9647ef29f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_history",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("adjust", "set_levels", name="inventory_change_kind"), nullable=False),
        sa.Column("quantity_on_hand_before", sa.Integer(), nullable=False),
        sa.Column("quantity_on_hand_after", sa.Integer(), nullable=False),
        sa.Column("reorder_level_before", sa.Integer(), nullable=False),
        sa.Column("reorder_level_after", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_history_product_id_created_at",
        "inventory_history",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("from_status", _EXISTING_ORDER_STATUS, nullable=True),
        sa.Column("to_status", _EXISTING_ORDER_STATUS, nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "order_created",
                "payment",
                "manual",
                "customer_cancel",
                "shipment_created",
                "shipment_dispatched",
                "shipment_delivered",
                name="order_status_change_source",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"), "order_status_history", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_status_history_order_id"), table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index("ix_inventory_history_product_id_created_at", table_name="inventory_history")
    op.drop_table("inventory_history")
    # drop_table does not drop the enum types create_table made.
    sa.Enum(name="order_status_change_source").drop(op.get_bind())
    sa.Enum(name="inventory_change_kind").drop(op.get_bind())
    # ### end Alembic commands ###
